### PR TITLE
x-mojo-over feature

### PR DESCRIPTION
**Pull request by onokhov**
New `x-mojo-over` key is an ability to create mojolicious routes with conditions passed to Mojolicious::Routes::Route::over

### CODE REVIEW

**Comment by jhthorsen** [comment]
Hey, and thank you for the PR.

I was wondering how this is covered in the OpenAPI spec and/or how this apply to a usecase in the real world.

The diff is so small, that I would like to take it, but without a proper usecase, it’s hard to accept it. Also, it needs a unit test.

**Comment by onokhov** [comment]
I need `x-mojo-over` key to use Mojolicious::Plugin::Authorization plugin
I can control access to api methods based on user privileges with it.
Something like
`"x-mojo-over": [ "is_role": "admin" ]`
`"x-mojo-over": [ "has_priv": "delete" ]`

**Comment by jhthorsen** [comment]
I that case, I don't think I will take it, since you should rather use https://metacpan.org/pod/Mojolicious::Plugin::OpenAPI::Security

**Comment by onokhov** [comment]
Thank you. Mojolicious::Plugin::OpenAPI::Security is a correct way

**Comment by jhthorsen** [comment]
Awesome! Glad that you can use ::Security 👍

**Pull request closed without merging**
