### PR TITLE
Add support for new JSON::Validator schema API

### PR DESCRIPTION
**Pull request by jhthorsen**
This PR has support for the new schema classes in JSON::Validator 4.11.

- https://metacpan.org/pod/JSON::Validator::Schema::OpenAPIv2
- https://metacpan.org/pod/JSON::Validator::Schema::OpenAPIv3

These classes will replace JSON::Validator::OpenAPI::Mojolicious.

The external API should have no significant changes, but the validation error messages has changed a bit:

- The "path" in errors are prefixed with "/body" or the name of the "body" param in v2.
- Messages has changed if there are no "body".
- Invalid "Accept" header results in 400 Bad Request, instead of 500 Internal Server Error

Other things:

- OpenAPI version gets auto-discovered from schema - No need for setting "schema" to "v2" or "v3" when loading the plugin anymore
- Add Mojolicious::Plugin::OpenAPI::Parameters with the following helpers
  - $c->openapi->build_response_body()
  - $c->openapi->build_schema_request()
  - $c->openapi->build_schema_response()
  - $c->openapi->coerce_mojolicious_request()
  - $c->openapi->coerce_mojolicious_response()
  - $c->openapi->parse_request_body()

Please try this PR out and let me know of any regressions!

### CODE REVIEW

**Comment by shubhaguha** [comment]
Just curious now that you have pointed me to this from my PR, do you happen to have an approximate ETA for this? :)

**Comment by jhthorsen** [comment]
No, I don't have an ETA, but this is my focus when I have free time. https://github.com/mojolicious/json-validator/pull/189 has gotten more tests now and a much more user friendly API, but it's not quite there yet unfortunately. I think cleaning up M::P::OpenAPI will be very easy after I'm done with J::V.

**Comment by jhthorsen** [comment]
This branch is ready now. Please try it out 👍

**Comment by zakame** [comment]
Hi, @jhthorsen, nice work!

Would this change now mean that https://metacpan.org/pod/OpenAPI::Client is obsolete?  Currently that module has broken tests now that `JSON::Validator::OpenAPI::Mojolicious` is gone.

**Comment by jhthorsen** [comment]
That's awful. I totally forgot about it... I'll try to find time to fix it soon.

**Comment by jhthorsen** [comment]
OpenAPI::Client is soon available on CPAN.

**Comment by zakame** [comment]
Awesome, thanks for the update!

**Pull request merged**
