### PR TITLE
Add fallback to default renderer, unless "openapi" is set in stash

### PR DESCRIPTION
**Pull request by jhthorsen**
Opening this PR, since I'm not sure if it's a good idea or not.

### CODE REVIEW

**Comment by mrenvoize** [comment]
I must admit, I'm not entirely sure of the scenario for when this would be needed?

**Comment by jhthorsen** [comment]
The scenario was encountered by @marcusramberg. The code is something like this:

```
sub send_email {
  my $c     = shift->openapi->valid_input or return;
  my $email = $c->render_to_string("mails/generic", format => "html");
  my $sent  = $c->send_email($email);

  $c->render(openapi => {sent => $sent});
}
```

Calling `render_to_string()` inside an openapi action, will have "handler" (in stash) set to "openapi" and not "ep", which results in `$email` being `undef`, since the template "mails/generic.html.openapi" is not found.

**Comment by mrenvoize** [comment]
Oh, wow.. that makes sense now..  I'll re-read the code with that in mind now.

**Comment by jhthorsen** [comment]
Anybody? I'm about to close this, if no-one can tell me if it's a good idea or not :(

**Comment by mrenvoize** [comment]
Well, I ended up not having a hard opinion for or against this.. @marcusramberg could do with commenting really if it was him that raised it?

**Comment by marcusramberg** [comment]
I'm pro this change, since it was very surprising to me that render didn't work. Can't really say if there's a better way to make OpenAPI work more transparently with other renderers tho.

**Comment by jhthorsen** [comment]
Ok. Merging this now. Let us rather revert it if someone reports in bugs.

Just a final question: How do you like the sound in 36d4043? Also, should it log with warn instead of debug?

**Pull request merged**
