### PR TITLE
Fix "renderer" will also be called for "invalid input" and "internal errors

### LINKED ISSUE #34: Ability to change the format of the "Default error document"
Is it currently possible?

### PR DESCRIPTION
**Pull request by jhthorsen**
This PR is a proposal to fix #34 - Ability to change the format of the "Default error document".

Does anyone have an idea on how to fix the 404 response?

@leejo: This change removes the "openapi.not_implemented" helper. You might want to check if the code can still work for you.

### CODE REVIEW

**Comment by leejo** [comment]
> @leejo: This change removes the "openapi.not_implemented" helper. You might want to check if the code can still work for you.

What's it been replaced with? Renderer?

**Comment by leejo** [comment]
Yep, this breaks our [emulator](https://github.com/Humanstate/payprop_api_emulator) and my planned conference [talk](https://github.com/leejo/emulating_any_api). I'll look at fixing sometime this week.

**Comment by jhthorsen** [comment]
"renderer" has always been here, but it haven't been in use for "internal server" errors and friends. This is now fixed.

At the same time, I would like to remove the openapi.not_implemented helper, since it feels redundant now. The idea is a simpler API and less maintenance.

**Comment by le-garff-yoann** [comment]
It's OK for me, these changes meet my needs.

**Comment by jhthorsen** [comment]
Cool! I figured out the 404 part, so I will merge and make a new release tomorrow.

**Pull request merged**
