### PR TITLE
Render html description fields with Text::Markdown

### PR DESCRIPTION
**Pull request by tagg**
Improve rendering of html-formatted spec, by running `description` fields through Text::Markdown.

### CODE REVIEW

**Comment by jhthorsen** [comment]
I like your change, but I don't like the HTML renderer I've written, so I don't want to take this change.

I'm still looking for a better ways to render the specification, either with an overhaul of what I've done or with an external tool that can be bundled. The biggest issue I have with the current renderer is how it represents responses and complex request data structures. What I do like about this renderer, that the other I've seen seems to lack is the possibility to print/export as PDF and send it to some external consumer.

Gonna leave this open for others to comment, or just to bug me enough to add a better doc renderer.

**Comment by jhthorsen** [comment]
@tagg: How do you feel about making Text::Markdown an optional module?

**Comment by tagg** [comment]
@jhthorsen: That would totally work.

**Comment by jhthorsen** [comment]
Cool! 👍

**Pull request merged**
