### PR TITLE
Add simple CORS support

### PR DESCRIPTION
**Pull request by jhthorsen**

### CODE REVIEW

**Comment by ugexe** [comment]
Could someone explain where this enhancement currently stands? As in: what still needs to be planned and what still needs to be implemented? Not sure I can help on the planning portion, but I can contribute implementation wise if I know where things stand and what is left.

**Comment by jhthorsen** [comment]
@ugexe: It's been a long time since I worked on this, so I'm not sure what is missing. I just rebased master into this branch, so if you like, you can try it out and let me know what doesn't work. Or if anything works at all.

**Comment by mohawk2** [comment]
Could this be rebased? I like the idea of plugins.

**Comment by jhthorsen** [comment]
@mohawk2: Done.

@ugexe: Should be able to test this branch now:

```
cpanm https://github.com/jhthorsen/mojolicious-plugin-openapi/archive/feature/cors.zip
```

Check the unit test for how to use it.

**Pull request merged**
