### PR TITLE
Pass exception to renderer

### PR DESCRIPTION
**Pull request by manuelm**

### CODE REVIEW

**Comment by jhthorsen** [comment]
This PR need to have tests and a usecase as well.

**Comment by manuelm** [comment]
Sure. I'll add tests later. Use case is to extract information from exception / distinguish between different exceptions in custom renderer. e.g. sending an error message including part of the exception object/string to the client.

**Comment by mrenvoize** [comment]
I think I'd be much happier with this if I could see an example of the custom renderer your building @manuelm, right not I'm not 100% sure what you're trying to achieve/how you're trying to achieve it.

Personally, I just use the bundled error document specification and create errors that match it for my own pre-validation errors. I'm happy to accept this isn't necessarily the best approach and think that's what your trying to work around here?

**Comment by jhthorsen** [comment]
I wonder if the exception message is eaten..? Or is it logged as usual?

**Comment by manuelm** [comment]
Yes, the exception doesn't get passed to the custom renderer at all.

Right now if you throw an exception, e.g using `Mojo::Exception->throw({foo => "bar""})` or `die("something bad happened")` all only know is that an exception/die/... occured by the looking at the status code. But you cannot access the actual message/object.

Do you really want to take a look at my renderer?

**Comment by jhthorsen** [comment]
What I meant is: Does the exception get logged?

**Comment by manuelm** [comment]
> What I meant is: Does the exception get logged?

I'm not sure I fully understand your question. Yes, the exceptions get's logged by Mojolicious. That's because the `reply.exception` helper first logs the exception before calling the (openapi) renderer. See  https://github.com/kraih/mojo/blob/master/lib/Mojolicious/Plugin/DefaultHelpers.pm#L91.

**Comment by manuelm** [comment]
I've added a simple test to `t/renderer.t`.

**Comment by jhthorsen** [comment]
Looks good to me! Thanks for adding the test 👍

**Comment by mrenvoize** [comment]
Glad we got there,  sorry I wasn't much help in reviewing.

_Sent from my Sony D5803 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
